### PR TITLE
fix: do not reset storages

### PR DESCRIPTION
**Pull request by paavo**
As a dev requirement in composer.json `flownative/flow-resourceproxy` gets loaded after Distributionspackages. 
The `storages: []` will override already set storages.

### CODE REVIEW

**Comment by paavo** [comment]
@kitsunet as a follow-up to the composer-order discussion on Slack.

**Comment by paavo** [comment]
@kitsunet hope you find some time to review the PR
have a good weekend 🎉

**Review by kdambekalns — COMMENTED** [review]
This would reset all ResourceProxy settings, no?

How about removing the file and only providing an example in the README?

**Comment by paavo** [comment]
This is already documented here https://github.com/flownative/flow-resourceproxy#configuration @kdambekalns

**Comment by paavo** [comment]
I have updated my PR and removed the Settings.yaml file @kdambekalns

**Comment by paavo** [comment]
May you merge this PR @kdambekalns?

**Pull request merged**
